### ISSUE TITLE
Fails to download package

### ISSUE THREAD

**Issue by tzulberti** [tzulberti/Flask-PyPi-Proxy#2]
Right now, the current configuration fails to download:
- py-bcrypt
- redis

**Comment by tzulberti** [comment]
Ver de usar esto para solucionarlo:

http://alexis.notmyidea.org/distutils2/library/distutils2.index.simple.html#distutils2.index.simple.Crawler

En el distutils2 que estoy usando el la referencia es a: from distutils2.pypi.simple import Crawler

**Comment by rjarry** [comment]
Hello :-)

#6 should solve this problem

**Comment by tzulberti** [comment]
Closed because closed #6
